add stuff

diff --git a/clockwerk b/clockwerk
--- a/clockwerk
+++ b/clockwerk
@@ -29,21 +29,25 @@ LOCKFILE="${CW_DATADIR}/clockwerk.lock"
 
 debug() {
   local mesg=$1; shift
-  printf "%s\n" "$mesg"
+  printf "debug: %s\n" "$mesg"
 }
 
 die() {
-  :
+  local mesg=$1; shift
+  printf "error: %s\n" "$mesg"
 }
 
 warn() {
-  :
+  local mesg=$1; shift
+  printf "warn: %s\n" "$mesg"
 }
 
 info() {
   :
 }
 
+# return 0 on success
+# return 1 on failure
 initialize_db() {
   local sql="CREATE TABLE job(j_id INTEGER PRIMARY KEY AUTOINCREMENT,
                               j_category TEXT NOT NULL,
@@ -54,7 +58,9 @@ initialize_db() {
              CREATE TABLE category(c_name TEXT PRIMARY KEY,
                                    c_desc TEXT);"
 
-  exec_query "$sql"
+  exec_query "$sql" || return 1
+
+  return 0
 }
 
 exec_query() {
@@ -69,14 +75,13 @@ lock_acquire() {
   touch "$LOCKFILE" && return 0 || return 1
 }
 
-# returns nonzero (job_id) on success
-# returns 0 on failure
+# returns 0 on success
+# returns non-zero on failure
 lock_release() {
   debug "Releasing lock"
-  [[ ! -f $LOCKFILE ]] && return 0
-  local job_id=$(< "$LOCKFILE")
-  rm "$LOCKFILE" || return 0
-  return $job_id
+  [[ ! -f $LOCKFILE ]] && return 1
+  cat "$LOCKFILE"
+  rm "$LOCKFILE"
 }
 
 # return 0 on success
@@ -84,37 +89,30 @@ lock_release() {
 # return 2 on sql error
 job_start() {
   lock_acquire || return 1
-  local jobstart=$(date +%s)
-  local category=$1
-  local comment=$2
 
-  # insert into table
-  sql="INSERT INTO job(job_category, job_start, job_comment)
-                VALUES('$category', $jobstart, '$comment');"
+  local jobstart=$(date +%s) category=$1 comment=$2
 
-  exec_query "$sql" || return 2
-  local jobid=$(exec_query 'select max(job_id) from jobs;')
-
-  echo "$jobid $jobstart" > "$LOCKFILE"
+  echo "$jobstart|$category|$comment" > "$LOCKFILE"
 }
 
 # return 0 on success
-# return 1 on no job recorded (too short)
-# return 2 on error
+# return 1 on error
 job_stop() {
-  local jobid jobstart jobstop=$(date +%s)
-  read jobid jobstart <<< "$(lock_release)"
+  [[ ! -f $LOCKFILE ]] && return 1
+  local category jobstart comment jobstop=$(date +%s)
 
-  if [[ $(get_duration $jobstart $jobstop) -gt 60 ]]; then
-    job_delete $job_id
-    return 1
-  fi
+  IFS=$'|' read jobstart category comment <<< "$(lock_release || echo -1)"
 
-  local sql="UPDATE job SET job_stop = '$jobstart' WHERE job_id = '$jobid';"
+  [[ $jobstart -eq -1 ]] && return 1
+
+  [[ $(get_duration $jobstart $jobstop) -gt 60 ]] && return 2
+
+  local sql="INSERT INTO job(j_category, j_start, j_stop, j_comment)
+                      VALUES('$category', '$jobstart', '$jobstop', 'comment');"
 
   exec_query "$sql" &>/dev/null
 
-  [[ $jobid -eq 0 ]] && return 2
+  [[ $jobid -eq 0 ]] && return 3
 }
 
 # returns duration in seconds
@@ -136,15 +134,11 @@ date_to_seconds() {
 seconds_to_hms() {
   local seconds=$1 hours=0 minutes=0
 
-  while (( seconds >= 3600 )); do
-    (( ++hours ))
-    (( seconds -= 3600 ))
-  done
+  hours=$(( seconds / 3600 ))
+  seconds=$(( seconds - hours * 3600 ))
 
-  while (( seconds >= 60 )); do
-    (( ++minutes ))
-    (( seconds -= 60 ))
-  done
+  minutes=$(( seconds / 60 ))
+  seconds=$(( seconds - minutes * 60 ))
 
   echo $hours $minutes $seconds
 }
@@ -168,9 +162,11 @@ category_del() {
 
 do_job() {
   local action=$1; shift
+
   case $action in
     "start")
-      [[ $# -gt 0 ]] && job_start "$@" || usage
+      [[ -z $1 ]] && die "missing job category"
+      job_start "$@"
       ;;
     "stop")
       job_stop
@@ -178,19 +174,27 @@ do_job() {
     *) usage
       ;;
   esac
+
 }
 
 do_category() {
   local action=$1; shift
+
+  case $action in
+    "add") category_add "$@" ;;
+    *) die "Not implemented" ;;
+  esac
+
 }
 
 do_report() {
   local action=$1; shift
+
 }
 
 #sanity checks
 [[ ! -d $CW_DATADIR ]] && mkdir -p "$CW_DATADIR"
-exec_query 'SELECT * FROM job' &>/dev/null || initialize_db
+exec_query 'SELECT * FROM job' &>/dev/null || initialize_db || die "failed to initialize database"
 
 # option parsing
 action=$1; shift
